language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: 
  - "npm install uglify-js -g"
  - "npm install mocha -g"
  - "npm install express -g"
before_script: 
  - "make debug"
  - "node index_min.js &"
  - "sleep 15"
script: "mocha"
